---
- hosts: dev
  become: yes
  remote_user: ec2-user
  tasks:
    - name: remove old httpd and php
      yum:
        name: ['httpd*','php*']
        state: absent
    - name: clean yum repo
      command: yum clean all
      args:
        warn: false
    - name: yum update
      yum: name=* state=latest
    - name: Wait for yum lock release (Ansible 2.8.0 workaround)
      shell: ps -aux | grep yum
      register: yum_lock
      retries: 20
      delay: 6
      until: yum_lock.stdout_lines|length <= 2
      changed_when: false
    - name: Install Apache
      yum: 
        name: ['httpd24','php73','php73-mysqlnd']
        state: present
    - name: Download WordPress
      get_url: url=http://wordpress.org/wordpress-latest.tar.gz dest=/var/www/html/wordpress.tar.gz force=yes
    - name: Extract Wordpress
      command: "tar xzf /var/www/html/wordpress.tar.gz -C /var/www/html --strip-components 1"
    - name: make my directory tree readable
      file:
        path: /var/www/html
        mode: u=rwX,g=rX,o=rX
        recurse: yes
        owner: apache
        group: apache
    - name: Make sure Apache is started now and at boot.
      service: name=httpd state=started enabled=yes

